init python:
    def get_rpgm_items():
        return [
            {
                "id": 0,
                "key": "",
                "name": "",
                "description": "",
                "consumable": False,
                "price": 0,
                "note": "",
                "max_limit": None,
                "itype_id": 0,
            },
            {
                "id": 1,
                "key": "clothes",
                "name": "Clothes",
                "description": "Go see the photographer and give him the package",
                "consumable": False,
                "price": 0,
                "note": "",
                "max_limit": None,
                "itype_id": 0,
            },
            {
                "id": 2,
                "key": "tools_bag",
                "name": "Tools bag",
                "description": "Bring the tools to the worker at the festival site",
                "consumable": False,
                "price": 0,
                "note": "",
                "max_limit": None,
                "itype_id": 0,
            },
            {
                "id": 3,
                "key": "liqueur",
                "name": "Liqueur",
                "description": "Go to see the boys by night",
                "consumable": False,
                "price": 0,
                "note": "",
                "max_limit": None,
                "itype_id": 0,
            },
            {
                "id": 4,
                "key": "flowers",
                "name": "Flowers",
                "description": "Flowers for the hot springs",
                "consumable": False,
                "price": 0,
                "note": "",
                "max_limit": None,
                "itype_id": 0,
            },
        ]