init python:
    def rpgm_events_for_map(map_name):
        return rpgm_map_events.get(map_name, [])

    def rpgm_autoruns_for_map(map_name):
        return rpgm_map_autoruns.get(map_name, [])

    def rpgm_parallels_for_map(map_name):
        return rpgm_map_parallels.get(map_name, [])

    def rpgm_multiple_triggers_for_map(map_name):
        return rpgm_map_multiple_triggers.get(map_name, [])

    def rpgm_display_name(map_name):
        return rpgm_map_display_names.get(map_name, map_name)

    def get_rpgm_map_id(map_name):
        return rpgm_map_ids.get(map_name, 0)

    def get_rpgm_id_map(map_id):
        return rpgm_id_maps.get(map_id)

define rpgm_map_events = {
    "CommonEvents": [],
    "Town": [
        ("Townfotografo",_("Photographer")),
        ("TownCastlePoster",_("Read sign")),
        ("Towneventofotografiaintro",_("Talk to old man")),
        ("TownNPCwoman",_("Talk to woman")),
        ("TownMeetAlexa",_("Talk to woman")),
        ("TownNPCtourist3",_("Talk to tourist")),
        ("Townturista1_v2",_("Talk to tourist")),
        ("TownNPCtourist2",_("Talk to tourist")),
        ("TownNPCRelax",_("Talk to old villager")),
        ("TownDataCityPoster",_("Read sign")),
        ("TownToPoliceStation",_("To Police Station")),
        ("TownPolicePoster",_("Read sign")),
        ("TownMerchant",_("Talk to merchant")),
        ("TownStall",_("Talk to villager woman")),
        ("TownFleaMarket",_("Talk to villager girl")),
        ("TownToInn",_("To Inn")),
        ("TownToClothingStore",_("To Read sign")),
        ("TownToFoodStore",_("Enter store")),
        ("TownToPath",_("To Path")),
        ("TownNPCEntryFestival",_("Talk to festival worker")),
        ("TownNPCBrowser",_("Talk to villager")),
        ("TownSkirtLift",_("Look at stall")),
        ("Townhombrepaseando3",_("Talk to villager")),
        ("TownBoarInn",_("Read sign")),
        ("TownClothingSign",_("Read sign")),
        ("TownStoreSign",_("Read sign")),
        ("Townespacioentradafestival",_("To festival")),
        ("TownIShouldGoToTheInnJohannIsWaitingForMe_v10",_("To upper town")),
        ("TownIShouldGoToTheInnJohannIsWaitingForMe_v11",_("To market")),
        ("TownIShouldGoToTheInnJohannIsWaitingForMe_v12",_("To bar")),
        ("Townfinaldelprimerdia",_("Talk to Johan")),
        ("TownToRiverEvent",_("To river")),
        ("TownToRiver",_("To River")),
        ("TownNPCPADRE",_("Talk to father")),
        ("TownNPCOldMan",_("Talk to old man")),
        ("TownNPCkid",_("Talk to kid")),
        ("TownToHouseInterior",_("To House Interior")),
        ("TownNPCCantWait",_("Talk to man")),
        ("TownCorruptionCounter",_("Examine statue")),
        ("TownCorruptionFairy",_("Fairy")),
        ("TownIShouldGoToTheInnJohannIsWaitingForMe",_("To village green")),
        ("TownSeemsItsClosed",_("Door")),
        ("TownNPCmafioso",_("Talk to man")),
        ("TownTABLON",_("What to do today")),
        ("TownNPCVillageWoman",_("Talk to woman")),
        ("Townturista1",_("Talk to man")),
        ("TownGrave",_("Read enscription")),
        ("Townborracho",_("Talk to drunk old man")),
        ("TownToGlade",_("To glade")),
        ("TownNPCVillager",_("Talk to villager")),
        ("TownNPCCop",_("Talk to policeman")),
        ("TownToBar",_("Enter bar")),
        ("TownNPCDrunkEvent1",_("Talk to drunk")),
        ("Townborrachoinconsciente",_("Talk to drunk")),
        ("TownNPCDrunkEvent2",_("Talk to drunk")),
        ("Towneventolemetenmanobarrio",_("Talk to drunk")),
        ("TownPillar",_("Read sign")),
    ],
    "Inn": [
        ("InnToInnRooms",_("Up to the rooms")),
        ("Innposadero",_("Innkeeper")),
        ("InnNPCDiner",_("Guest")),
        ("InnNPCDrinker",_("Guest")),
        ("Innpan",_("Bread")),
        ("InnNPCEater",_("Guest")),
        ("InnCantLeave",_("Leave")),
        ("Innpapelesposada",_("Papers")),
        ("InnToTown",_("Leave")),
    ],
    "River": [
        ("RiverNPCEntranceMan",_("Talk to villager")),
        ("Riverimpedimentoparasalirrio",_("Leave")),
        ("RiverNPCRiverBucket",_("Talk to villager")),
        ("RiverNPCEventMan",_("Talk to villager")),
    ],
    "InnRooms": [
        ("InnRoomspersonabao",_("Guest")),
        ("InnRoomsSleep",_("Go to sleep")),
        ("InnRoomsnio",_("Go into room")),
        ("InnRoomsDEJANDOlasmaletas",_("Go into your room")),
        ("InnRoomsIchaIchaParadiseAuthorJiraiya",_("Read magazine on table")),
        ("InnRoomsToInn",_("Go downstairs")),
    ],
    "Festival": [
        ("FestivalToPath",_("Leave the festival site")),
        ("FestivalButtPlugEvent",_("Work at the food stall")),
        ("FestivalFoodStand",_("Talk to Johan")),
        ("FestivalNPCSkint",_("Talk to villager")),
        ("Festivalworkerdentrofestival",_("Talk to festival worker")),
        ("FestivalNPCCompliment",_("Talk to villager")),
        ("FestivalNPCHeyCutie",_("Talk to villager")),
        ("FestivalNPCShrooms",_("Talk to villager")),
        ("FestivalNPCNiceTits",_("Talk to villager")),
        ("FestivalMassageParlor",_("To Massage Parlor")),
        ("FestivalNPCFruit",_("Talk to villager")),
        ("FestivalPhotoSession",_("Talk to Johan")),
        ("FestivalFestivalWorkerSon",_("Talk to boy")),
        ("FestivalNPCLetch",_("Talk to villager")),
        ("FestivalNPCTourist",_("Talk to tourist")),
        ("FestivalSpyOnAlexa",_("Is that Alexa?")),
    ],
    "Bar": [
        ("BarNPCAbusive",_("Talk to patron")),
        ("BarNPCMachine",_("Talk to patron")),
        ("Barbarman",_("Talk to the barman")),
        ("BarNPCOldDrunk",_("Talk to patron")),
        ("BarNPCBuyDrink",_("Talk to patron")),
        ("BarNPCDadComplains",_("Talk to patron")),
        ("BarNPCthug1",_("Talk to patron")),
        ("BarNPCthug2",_("Talk to patron")),
        ("BarNPCthug5",_("Talk to patron")),
        ("BarNPCBadFood",_("Talk to patron")),
        ("BarNPCthug3",_("Talk to patron")),
        ("BarNPCthug4",_("Talk to patron")),
        ("BarBJGame",_("Sit at table")),
        ("BarToTown",_("Leave")),
    ],
    "FoodStore": [
        ("FoodStoreTheyHaveSoftDrinksOfAllFlavors",_("Look at the drinks")),
        ("FoodStoreMmmSpicyNoodles",_("Look at the food")),
        ("FoodStoreMerchant",_("Talk to the merchant")),
        ("FoodStoreToTown",_("Leave the store")),
        ("FoodStoreYouWonANewObject",_("Pick up tools bag")),
    ],
    "ClothingStore": [
        ("ClothingStoreHeyThere",_("Talk to merchant")),
        ("ClothingStoreToTown",_("Leave the store")),
        ("ClothingStoreIShouldComeBackLaterToTryTheFestivalClothes",_("Look at clothes")),
    ],
    "TownEntrance": [
        ("TownEntranceJohanmedia",_("Talk to Johan")),
        ("TownEntranceJohanAlta",_("Talk to Johan")),
    ],
    "Apartment": [
        ("ApartmentORDENADOR",_("Check the computer")),
        ("ApartmentNPCMUJER",_("Talk to Leyna")),
        ("Apartmentarmario",_("Check the closet")),
        ("Apartmenttelevision",_("Check the TV")),
        ("Apartmentlavabo",_("Take a drink")),
        ("Apartmentpuerta",_("Open the front door")),
    ],
    "Intro": [],
    "HouseInterior": [
        ("HouseInteriorpersonacasa1",_("Talk to the man")),
        ("HouseInteriormujercasa1",_("Talk to the woman")),
        ("HouseInteriorToTown",_("Leave")),
    ],
    "HotSpringsExterior": [
        ("HotSpringsExteriorToReception",_("Go to reception")),
        ("HotSpringsExteriorHotSpings",_("Look at sign")),
        ("HotSpringsExteriorToPath",_("Go back to the path")),
    ],
    "HotSpringsBathroom": [],
    "Reception": [
        ("Receptionrecepcion",_("Talk to the receptionist")),
        ("ReceptionToHotSpringsExterior",_("Leave the hot springs")),
    ],
    "Path": [
        ("PathToHotSpringsExterior",_("To Hot Springs")),
        ("PathLeynaWorkTrigger",_("To Hot Springs")),
        ("PathHotSpringsTown",_("Sign")),
        ("PathWowItLooksLikeTheHotspringsHaveReopened",_("To Hot Springs")),
        ("PathToTown",_("To Town")),
        ("Pathespacioentradafestival",_("Go to the festival")),
        ("PathNPCFestivalWorker",_("Talk to Festival Worker")),
        ("PathMeow",_("Cat")),
    ],
    "PhotographersHouse": [],
    "PoliceStation": [
        ("PoliceStationSorryYouCantBeHerePleaseGoToTheHall",_("Talk to police officer")),
        ("PoliceStationNPCCaptain",_("Talk to police captain")),
        ("PoliceStationeventocomisaria",_("Approach the cells")),
        ("PoliceStationToTown",_("Leave")),
    ],
    "Glade": [
        ("GladeToTown",_("Leave")),
        ("GladeWelcomeToTheCumZone",_("Look at sign")),
    ],
    "River2": [],
    "HotSprings": [],
    "Photoshoot2": [],
    "TownNight": [
        ("TownNightCastlePoster",_("Read sign")),
        ("TownNightNPCWhatALovelyNight",_("Talk to couple")),
        ("TownNightDataCityPoster",_("Read sign")),
        ("TownNightPoliceAsleep",_("Open door")),
        ("TownNightPolicePoster",_("Read sign")),
        ("TownNightToInnNight",_("To Boar Inn")),
        ("TownNightStoreClosed",_("Open door")),
        ("TownNightBoarInn",_("Read sign")),
        ("TownNightSorryWeAreClosing",_("Open door")),
        ("TownNightClothingSign",_("Read sign")),
        ("TownNightStoreSign",_("Read sign")),
        ("TownNightCorruptionCounter",_("Examine statue")),
        ("TownNightSeemsItsClosed",_("Door")),
        ("TownNightTABLON",_("What to do today")),
        ("TownNightNPCLoveIt",_("Talk to villager")),
        ("TownNightNPCParty",_("Talk to villager")),
        ("TownNightNPCSleep",_("Talk to villager")),
        ("TownNightEhhhYouuuuuuuuu",_("Talk to boys")),
        ("TownNightGrave",_("Read enscription")),
        ("TownNightPillar",_("Read sign")),
    ],
    "InnNight": [
        ("InnNightToInnRoomsNight",_("To Inn Rooms")),
        ("InnNightpan",_("Bread")),
        ("InnNightpapelesposada",_("Papers")),
        ("InnNightToTownNight",_("Leave")),
    ],
    "InnRoomsNight": [
        ("InnRoomsNightSleep",_("Go to sleep")),
        ("InnRoomsNightIchaIchaParadiseAuthorJiraiya",_("Read magazine on table")),
        ("InnRoomsNightToInnNight",_("Go downstairs")),
    ],
    "Town2": [
        ("Town2fotografo",_("Photographer")),
        ("Town2CastlePoster",_("Read sign")),
        ("Town2NPCFountainGuy",_("Talk to old villager")),
        ("Town2MeetPhotographer",_("Photographer")),
        ("Town2DataCityPoster",_("Read sign")),
        ("Town2LeynaJohanSex","LeynaJohanSex"),
        ("Town2ToPoliceStation",_("To Police Station")),
        ("Town2PolicePoster",_("Read sign")),
        ("Town2Merchant",_("Merchant")),
        ("Town2Stall",_("Stall")),
        ("Town2FleaMarket",_("Flea market")),
        ("Town2ToInn",_("To Inn")),
        ("Town2ToClothingStore",_("Enter store")),
        ("Town2ToFoodStore",_("Enter store")),
        ("Town2ToPath",_("To Path")),
        ("Town2hombrepaseando3",_("Talk to villager")),
        ("Town2IHaveToFindThatGuy",_("To Inn")),
        ("Town2BoarInn",_("Read sign")),
        ("Town2ClothingSign",_("Read sign")),
        ("Town2StoreSign",_("Read sign")),
        ("Town2ToRiver",_("To River")),
        ("Town2ToRiverEvent",_("To river")),
        ("Town2ToHouseInterior",_("Enter house")),
        ("Town2NPCCantWait",_("Talk to man")),
        ("Town2CorruptionCounter",_("Examine statue")),
        ("Town2CorruptionFairy",_("Fairy")),
        ("Town2NPCPissedUp",_("Talk to villager")),
        ("Town2Ah","Ah"),
        ("Town2HeySweetieDoYouWantToHaveAGoodTime",_("Talk to villagers")),
        ("Town2chicofestival",_("Talk to boy")),
        ("Town2SeemsItsClosed",_("Door")),
        ("Town2mafioso",_("Talk to shady-looking man")),
        ("Town2TABLON",_("What to do today")),
        ("Town2chicoencontrado",_("Talk to boy")),
        ("Town2NPCWomanAdvice",_("Talk to woman")),
        ("Town2NPCtourist1",_("Talk to man")),
        ("Town2NPCAnotherFestivalBoy",_("Talk to boy")),
        ("Town2Grave",_("Read enscription")),
        ("Town2borracho",_("Talk to drunk old man")),
        ("Town2ToGlade",_("To glade")),
        ("Town2NPCWorkersSon",_("Talk to boy")),
        ("Town2NPCVillager",_("Talk to villager")),
        ("Town2NPCCop",_("Talk to policeman")),
        ("Town2ToBar2",_("Enter bar")),
        ("Town2borrachoinconsciente",_("Talk to slumped figure")),
        ("Town2Pillar",_("Read sign")),
        ("Town2ToTownEntrance",_("Leave town")),
    ],
    "Bar2": [
        ("Bar2NPCBuyDrink",_("Talk to patron")),
        ("Bar2NPCMachine",_("Talk to patron")),
        ("Bar2barman",_("Talk to the barman")),
        ("Bar2NPCOldDrunk",_("Talk to patron")),
        ("Bar2NPCDadComplains",_("Talk to patron")),
        ("Bar2NPCBadFood",_("Talk to patron")),
        ("Bar2ToTown2",_("Leave")),
    ],
    "Mountains": [
        ("MountainsYouWonANewObject",_("Pick a flower")),
        ("MountainsYouWonANewObject_v2",_("Pick a flower")),
        ("MountainsYouWonANewObject_v3",_("Pick a flower")),
        ("MountainsYouWonANewObject_v4",_("Pick a flower")),
    ],
    "Casino": [],
    "MassageParlor": [
        ("MassageParlorToFestival",_("Go back to the festival site")),
    ],
    "TownFestivalNight": [
        ("TownFestivalNightCastlePoster",_("Read sign")),
        ("TownFestivalNightHesDrunkAgainMyHusbandCantHoldHisLiquor",_("Talk to villager wife")),
        ("TownFestivalNightNPCWhatALovelyNight",_("Talk to old couple")),
        ("TownFestivalNightOooohThisBeerIsGreatHehehehe",_("Talk to villager husband")),
        ("TownFestivalNightDataCityPoster",_("Read sign")),
        ("TownFestivalNightPoliceAsleep",_("Open door")),
        ("TownFestivalNightPolicePoster",_("Read sign")),
        ("TownFestivalNightToInnNight",_("To Inn")),
        ("TownFestivalNightStoreClosed",_("Open door")),
        ("TownFestivalNightimpedimento",_("To Inn")),
        ("TownFestivalNightBoarInn",_("Read sign")),
        ("TownFestivalNightClothingSign",_("Read sign")),
        ("TownFestivalNightStoreSign",_("Read sign")),
        ("TownFestivalNightMinesBigger",_("Talk to naked villager")),
        ("TownFestivalNightNoMinesWaaaayBiggerPal",_("Talk to naked villager")),
        ("TownFestivalNightCorruptionCounter",_("Examine statue")),
        ("TownFestivalNightGoodNightCouple",_("Talk to old man")),
        ("TownFestivalNighteventoescondite",_("Talk to Alexa")),
        ("TownFestivalNightIShouldLookForJohanThisGameHasGoneLongerThanIdLike",_("Go back to town")),
        ("TownFestivalNightSeemsItsClosed",_("Door")),
        ("TownFestivalNightThisFoodIsAmazingYouHaveToTryThis",_("Talk to villager")),
        ("TownFestivalNightTheFoodIsGoodButTheWineCouldBeBetter",_("Talk to villager")),
        ("TownFestivalNightShhhhImMeetingAVeryCuteTourist",_("Talk to young villager")),
        ("TownFestivalNightGodBlessThisFestivitieHehehe",_("Talk to villager")),
        ("TownFestivalNightPartyyyy",_("Talk to villager")),
        ("TownFestivalNighteventoblackmail",_("Talk to boys")),
        ("TownFestivalNightWhereTheHellHaveMyFriendsGone",_("Talk to tourist")),
        ("TownFestivalNightUgghghhh",_("Talk to villager")),
        ("TownFestivalNightGrave",_("Read enscription")),
        ("TownFestivalNightHeyLeaveMeAlonePlease",_("Talk to villager")),
        ("TownFestivalNightIOverdidItWithTheLiquorMyWifeIsGoingToKillMe",_("Talk to old villager")),
        ("TownFestivalNightPillar",_("Read sign")),
    ],
    "HotSpringsWithJohan": [],
    "FestivalNight": [
        ("FestivalNightnosalida",_("Leave")),
        ("FestivalNightLeynaropa",_("Leave")),
        ("FestivalNightWheresMyFriendGoneAFewMinutesAgoHeWasHereEatingAHotDog",_("Talk to villager")),
        ("FestivalNightNPCVomit",_("Talk to villager")),
        ("FestivalNightThosePillsTheyGaveMeToHellWithThem",_("Talk to villager")),
        ("FestivalNightICantGoDressedLikeThisWhatWouldJohanThink",_("Continue")),
        ("FestivalNightasd",_("Talk to villager")),
        ("FestivalNightGoodNightLeynayouAreAsSexyAsEver",_("Talk to drunk villager")),
        ("FestivalNightOhHeHelloHideTheErectionIHopeSheWillNotNotice",_("Talk to drunk villager")),
        ("FestivalNightFoodStand",_("Talk to chef")),
        ("FestivalNightMassageParlor",_("To Massage Parlor")),
    ],
    "FestivalFinale": [
        ("FestivalFinaleHeyGoodToSeeYouLeynaEspeciallyInThisSituationHehehehehe",_("Talk to villager")),
        ("FestivalFinaleOhLeynaIWasHopingToMeetYouIHaveSomethingToGiveYou",_("Talk to drunk villager")),
        ("FestivalFinaleDoYouWantSomeMasksForTheFinalEvent",_("Talk to villager")),
        ("FestivalFinaleHeyLeynaGoodToSeeYouHere",_("Talk to drunk villager")),
        ("FestivalFinaleAMassageWait",_("To massage parlor")),
        ("FestivalFinaleYoSlap",_("Talk to villager")),
        ("FestivalFinaleHeyWhatsGoingOnHere",_("Talk to group")),
        ("FestivalFinaleevent_15",_("Talk to photographer")),
        ("FestivalFinaleToCasinoFinale",_("Continue")),
    ],
    "CasinoFinale": [],
    "ApartmentEnding": [
        ("ApartmentEndingORDENADOR",_("Use the computer")),
        ("ApartmentEndingarmario",_("Go to the wardrobe")),
        ("ApartmentEndingtelevision",_("Turn on the TV")),
        ("ApartmentEndinglavabo",_("Go to the sink")),
        ("ApartmentEndingpuerta",_("Leave")),
    ],
    "ApartmentGroundFloor": [
        ("ApartmentGroundFloorarmario",_("Go to the wardrobe")),
        ("ApartmentGroundFloortelevision",_("Turn on the TV")),
        ("ApartmentGroundFloorlavabo",_("Go to the sink")),
    ],
}

define rpgm_map_autoruns = {
    "CommonEvents": [],
    "Town": [
        "TownNPCCop",
    ],
    "Inn": [
        "Innposadero",
        "InnSueojohanpart2",
        "Inninicionochefiesta",
        "InneventoJohanyalexa",
        "InnToInn",
    ],
    "River": [
        "Riverentradario",
    ],
    "InnRooms": [
        "InnRoomssueojohan",
        "InnRoomsescenadildo",
        "InnRoomsMyHeadIsKillingMeSeemsLikeYesterdayWeHadTooMuchToDrinkAgainICanBarelyRememberWhatHappened",
        "InnRoomsJohanHasntSleptHereTonightWhereIsHeIShouldLookForHimOrNotMaybeHesAtTheBusStop",
    ],
    "Festival": [
        "Festivalintrofestival",
        "Festivalintrosorteo",
        "Festivaliniciacionadolescencia",
    ],
    "Bar": [
        "BarWetTShirt",
    ],
    "FoodStore": [],
    "ClothingStore": [],
    "TownEntrance": [
        "TownEntranceparadabus",
        "TownEntranceCbajaending",
    ],
    "Apartment": [],
    "Intro": [
        "IntroHelloMyNameIsJohan",
    ],
    "HouseInterior": [],
    "HotSpringsExterior": [],
    "HotSpringsBathroom": [
        "HotSpringsBathroomeventoenseatrabajo",
    ],
    "Reception": [
        "Receptioneventohotsprings",
        "ReceptionDamn",
        "Receptionhotspringsjuntos",
    ],
    "Path": [
        "PathJohan",
    ],
    "PhotographersHouse": [
        "PhotographersHousesesionfotografica1",
    ],
    "PoliceStation": [],
    "Glade": [
        "GladeImSureHeWontFindMeHereThisAreaIsALittleScaryAtNightThough",
        "Gladecontinuacionfestival",
    ],
    "River2": [
        "River2ThisPlaceIsBeautiful",
    ],
    "HotSprings": [
        "HotSpringshotspringseventopart2",
    ],
    "Photoshoot2": [
        "Photoshoot2Sesionfotografica2",
    ],
    "TownNight": [],
    "InnNight": [
        "InnNightSleep",
        "InnNightentradaalaposadanoche",
    ],
    "InnRoomsNight": [],
    "Town2": [
        "Town2NPCCop",
        "Town2eventoflashback",
        "Town2JohanIWasLookingForYou",
        "Town2Flashback",
        "Town2ThinkIShouldGoToTheBusStopItShouldBeAboutToArrive",
    ],
    "Bar2": [
        "Bar2WowGuysWhatACoincidence",
        "Bar2Eventoanal1",
        "Bar2LeynaWeWereLookingForYou",
        "Bar2ToBar2",
        "Bar2LeynawhatAreYouDoingHereIThoughtYouWereLeavingTownThisMorning",
    ],
    "Mountains": [
        "MountainsWowThisPlaceIsBeautiful",
    ],
    "Casino": [
        "Casinohombredelasuerte",
    ],
    "MassageParlor": [
        "MassageParlorICantWaitToHaveARelaxingMassage",
    ],
    "TownFestivalNight": [],
    "HotSpringsWithJohan": [
        "HotSpringsWithJohanhotspringjuntoscont",
    ],
    "FestivalNight": [],
    "FestivalFinale": [
        "FestivalFinaleWellHereWeAre",
        "FestivalFinaleAltavozPleaseComeToTheGameRoomTheFinalEventOfTheFestivalIsAboutToBegin",
    ],
    "CasinoFinale": [
        "CasinoFinaleLooksLikeTheLastEventIsGoingToBeHere",
    ],
    "ApartmentEnding": [
        "ApartmentEndingCbajaending2",
        "ApartmentEndingCbajaending2_v2",
    ],
    "ApartmentGroundFloor": [
        "ApartmentGroundFloorCbajaending2",
    ],
}

define rpgm_map_parallels = {
    "CommonEvents": [],
    "Town": [
        "Townmusicapueblo",
        "TownMeetAlexa",
        "TownCorruptionFairy",
        "TownEV090",
    ],
    "Inn": [
        "Innmusicaposada",
    ],
    "River": [],
    "InnRooms": [],
    "Festival": [
        "FestivalNPCShrooms",
        "FestivalNPCNiceTits",
        "FestivalNPCFruit",
        "FestivalNPCHeyCutie",
        "FestivalNPCSkint",
        "FestivalNPCCompliment",
        "FestivalFestivalWorkerSon",
        "FestivalNPCLetch",
        "FestivalNPCTourist",
    ],
    "Bar": [],
    "FoodStore": [],
    "ClothingStore": [],
    "TownEntrance": [],
    "Apartment": [
        "Apartmentmusicapiso",
    ],
    "Intro": [],
    "HouseInterior": [],
    "HotSpringsExterior": [],
    "HotSpringsBathroom": [],
    "Reception": [],
    "Path": [
        "PathEV013",
    ],
    "PhotographersHouse": [],
    "PoliceStation": [],
    "Glade": [],
    "River2": [],
    "HotSprings": [],
    "Photoshoot2": [],
    "TownNight": [
        "TownNightmusicapueblo",
    ],
    "InnNight": [
        "InnNightmusicaposada",
    ],
    "InnRoomsNight": [],
    "Town2": [
        "Town2EV018",
        "Town2musicapueblo",
        "Town2CorruptionFairy",
        "Town2EV090",
        "Town2EV091",
    ],
    "Bar2": [],
    "Mountains": [],
    "Casino": [],
    "MassageParlor": [],
    "TownFestivalNight": [
        "TownFestivalNightmusicapueblo",
    ],
    "HotSpringsWithJohan": [],
    "FestivalNight": [],
    "FestivalFinale": [
        "FestivalFinaleEV012",
    ],
    "CasinoFinale": [],
    "ApartmentEnding": [],
    "ApartmentGroundFloor": [],
}

define rpgm_map_multiple_triggers = {
    "CommonEvents": [],
    "Town": [
        "TownNPCCop",
    ],
    "Inn": [
        "Innposadero",
    ],
    "River": [],
    "InnRooms": [],
    "Festival": [],
    "Bar": [],
    "FoodStore": [],
    "ClothingStore": [],
    "TownEntrance": [],
    "Apartment": [],
    "Intro": [],
    "HouseInterior": [],
    "HotSpringsExterior": [],
    "HotSpringsBathroom": [],
    "Reception": [],
    "Path": [],
    "PhotographersHouse": [],
    "PoliceStation": [],
    "Glade": [],
    "River2": [],
    "HotSprings": [],
    "Photoshoot2": [],
    "TownNight": [],
    "InnNight": [],
    "InnRoomsNight": [],
    "Town2": [
        "Town2NPCCop",
    ],
    "Bar2": [],
    "Mountains": [],
    "Casino": [],
    "MassageParlor": [],
    "TownFestivalNight": [],
    "HotSpringsWithJohan": [],
    "FestivalNight": [],
    "FestivalFinale": [],
    "CasinoFinale": [],
    "ApartmentEnding": [],
    "ApartmentGroundFloor": [],
}

define rpgm_map_display_names = {
}

define rpgm_map_ids = {
    "Town": 1,
    "Inn": 2,
    "River": 3,
    "InnRooms": 4,
    "Festival": 5,
    "Bar": 6,
    "FoodStore": 7,
    "ClothingStore": 8,
    "TownEntrance": 9,
    "Apartment": 10,
    "Intro": 11,
    "HouseInterior": 12,
    "HotSpringsExterior": 13,
    "HotSpringsBathroom": 14,
    "Reception": 15,
    "Path": 16,
    "PhotographersHouse": 17,
    "PoliceStation": 18,
    "Glade": 19,
    "River2": 20,
    "HotSprings": 21,
    "Photoshoot2": 22,
    "TownNight": 23,
    "InnNight": 24,
    "InnRoomsNight": 25,
    "Town2": 26,
    "Bar2": 27,
    "Mountains": 28,
    "Casino": 29,
    "MassageParlor": 30,
    "TownFestivalNight": 31,
    "HotSpringsWithJohan": 32,
    "FestivalNight": 33,
    "Gallery": 34,
    "FestivalFinale": 35,
    "CasinoFinale": 36,
    "ApartmentEnding": 37,
    "ApartmentGroundFloor": 38,
}

define rpgm_id_maps = {
    1: "Town",
    2: "Inn",
    3: "River",
    4: "InnRooms",
    5: "Festival",
    6: "Bar",
    7: "FoodStore",
    8: "ClothingStore",
    9: "TownEntrance",
    10: "Apartment",
    11: "Intro",
    12: "HouseInterior",
    13: "HotSpringsExterior",
    14: "HotSpringsBathroom",
    15: "Reception",
    16: "Path",
    17: "PhotographersHouse",
    18: "PoliceStation",
    19: "Glade",
    20: "River2",
    21: "HotSprings",
    22: "Photoshoot2",
    23: "TownNight",
    24: "InnNight",
    25: "InnRoomsNight",
    26: "Town2",
    27: "Bar2",
    28: "Mountains",
    29: "Casino",
    30: "MassageParlor",
    31: "TownFestivalNight",
    32: "HotSpringsWithJohan",
    33: "FestivalNight",
    34: "Gallery",
    35: "FestivalFinale",
    36: "CasinoFinale",
    37: "ApartmentEnding",
    38: "ApartmentGroundFloor",
}

define rpgm_common_event_switches = {
}

define event_xys = {
    "TownBoarInn": (29, 21),
    "TownToInn": (28, 20),
    "TownToRiver": (49, 23),
    "TownToBar": (25, 45),
    "TownToFoodStore": (43, 20),
    "TownToClothingStore": (36, 20),
    "TownToHouseInterior": (6, 27),
    "TownSeemsItsClosed": (13, 32),
    "TownNPCOldMan": (21, 24),
    "TownCastlePoster": (10, 6),
    "TownNPCEntryFestival": (1, 21),
    "Townespacioentradafestival": (1, 22),
    "TownToRiverEvent": (48, 23),
    "TownNPCCop": (17, 45),
    "Townturista1": (16, 36),
    "Townborrachoinconsciente": (41, 45),
    "TownStall": (13, 20),
    "TownMerchant": (9, 20),
    "TownFleaMarket": (17, 20),
    "TownNPCVillageWoman": (7, 36),
    "TownNPCwoman": (8, 7),
    "Townturista1_v2": (7, 8),
    "TownNPCtourist2": (9, 8),
    "TownNPCtourist3": (13, 7),
    "TownNPCCantWait": (9, 27),
    "TownNPCmafioso": (45, 33),
    "Townborracho": (45, 40),
    "TownNPCVillager": (4, 45),
    "TownToPoliceStation": (3, 20),
    "TownPolicePoster": (6, 20),
    "TownDataCityPoster": (23, 11),
    "TownPillar": (24, 48),
    "TownNPCDrunkEvent1": (40, 45),
    "TownNPCDrunkEvent2": (42, 45),
    "Towneventolemetenmanobarrio": (41, 46),
    "TownNPCPADRE": (17, 24),
    "TownNPCkid": (17, 25),
    "TownSkirtLift": (12, 21),
    "TownNPCRelax": (22, 8),
    "Townhombrepaseando3": (24, 21),
    "TownNPCBrowser": (10, 21),
    "TownClothingSign": (37, 21),
    "TownStoreSign": (45, 21),
    "Townfinaldelprimerdia": (41, 23),
    "TownToPath": (0, 21),
    "Townfotografo": (18, 5),
    "Towneventofotografiaintro": (18, 6),
    "TownToGlade": (49, 42),
    "TownMeetAlexa": (9, 7),
    "TownGrave": (13, 40),
    "TownCorruptionCounter": (20, 27),
    "TownCorruptionFairy": (21, 27),
    "TownIShouldGoToTheInnJohannIsWaitingForMe": (38, 31),
    "TownIShouldGoToTheInnJohannIsWaitingForMe_v10": (24, 22),
    "TownIShouldGoToTheInnJohannIsWaitingForMe_v11": (24, 23),
    "TownIShouldGoToTheInnJohannIsWaitingForMe_v12": (24, 23),
    "TownTABLON": (18, 34),
    "InnToTown": (8, 12),
    "InnToInnRooms": (1, 0),
    "Innposadero": (12, 4),
    "InnCantLeave": (8, 11),
    "InnNPCEater": (3, 9),
    "InnNPCDrinker": (1, 6),
    "InnNPCDiner": (2, 5),
    "Innpapelesposada": (14, 11),
    "Innpan": (12, 6),
    "Riverimpedimentoparasalirrio": (0, 8),
    "RiverNPCEntranceMan": (1, 7),
    "RiverNPCRiverBucket": (6, 9),
    "RiverNPCEventMan": (10, 9),
    "InnRoomsDEJANDOlasmaletas": (10, 13),
    "InnRoomsnio": (18, 11),
    "InnRoomsToInn": (6, 18),
    "InnRoomspersonabao": (4, 7),
    "InnRoomsIchaIchaParadiseAuthorJiraiya": (18, 15),
    "InnRoomsSleep": (12, 9),
    "FestivalToPath": (11, 0),
    "Festivalworkerdentrofestival": (12, 5),
    "FestivalNPCShrooms": (18, 9),
    "FestivalNPCNiceTits": (19, 9),
    "FestivalNPCFruit": (9, 15),
    "FestivalNPCHeyCutie": (2, 7),
    "FestivalNPCSkint": (17, 4),
    "FestivalNPCCompliment": (7, 6),
    "FestivalFestivalWorkerSon": (23, 15),
    "FestivalNPCLetch": (2, 16),
    "FestivalSpyOnAlexa": (22, 23),
    "FestivalFoodStand": (16, 4),
    "FestivalNPCTourist": (8, 21),
    "FestivalPhotoSession": (12, 15),
    "FestivalMassageParlor": (5, 15),
    "FestivalButtPlugEvent": (14, 2),
    "BarToTown": (8, 12),
    "Barbarman": (6, 4),
    "BarNPCMachine": (12, 3),
    "BarNPCAbusive": (8, 3),
    "BarNPCBuyDrink": (8, 5),
    "BarNPCOldDrunk": (15, 4),
    "BarNPCDadComplains": (1, 7),
    "BarNPCBadFood": (1, 9),
    "BarNPCthug1": (9, 7),
    "BarNPCthug2": (8, 8),
    "BarNPCthug3": (6, 9),
    "BarNPCthug4": (7, 9),
    "BarNPCthug5": (10, 8),
    "BarBJGame": (9, 9),
    "FoodStoreToTown": (10, 7),
    "FoodStoreTheyHaveSoftDrinksOfAllFlavors": (1, 3),
    "FoodStoreMmmSpicyNoodles": (4, 3),
    "FoodStoreMerchant": (7, 4),
    "FoodStoreYouWonANewObject": (1, 10),
    "ClothingStoreToTown": (9, 7),
    "ClothingStoreHeyThere": (5, 3),
    "ClothingStoreIShouldComeBackLaterToTryTheFestivalClothes": (1, 10),
    "TownEntranceJohanmedia": (7, 4),
    "TownEntranceJohanAlta": (8, 4),
    "ApartmentNPCMUJER": (13, 4),
    "ApartmentORDENADOR": (6, 3),
    "Apartmenttelevision": (5, 8),
    "Apartmentarmario": (3, 7),
    "Apartmentlavabo": (14, 8),
    "Apartmentpuerta": (1, 12),
    "HouseInteriorpersonacasa1": (1, 6),
    "HouseInteriormujercasa1": (11, 11),
    "HouseInteriorToTown": (4, 12),
    "HotSpringsExteriorToReception": (11, 7),
    "HotSpringsExteriorHotSpings": (13, 8),
    "HotSpringsExteriorToPath": (11, 12),
    "Receptionrecepcion": (5, 8),
    "ReceptionToHotSpringsExterior": (5, 12),
    "Pathespacioentradafestival": (0, 10),
    "PathToHotSpringsExterior": (11, 0),
    "PathHotSpringsTown": (14, 7),
    "PathToTown": (36, 9),
    "PathMeow": (17, 11),
    "PathNPCFestivalWorker": (5, 10),
    "PathLeynaWorkTrigger": (11, 5),
    "PathWowItLooksLikeTheHotspringsHaveReopened": (13, 8),
    "PoliceStationNPCCaptain": (13, 7),
    "PoliceStationSorryYouCantBeHerePleaseGoToTheHall": (5, 5),
    "PoliceStationToTown": (14, 12),
    "PoliceStationeventocomisaria": (6, 10),
    "GladeWelcomeToTheCumZone": (7, 7),
    "GladeToTown": (0, 5),
    "TownNightBoarInn": (29, 21),
    "TownNightToInnNight": (28, 20),
    "TownNightStoreClosed": (44, 20),
    "TownNightCorruptionCounter": (20, 27),
    "TownNightSeemsItsClosed": (13, 32),
    "TownNightCastlePoster": (10, 6),
    "TownNightPoliceAsleep": (3, 20),
    "TownNightPolicePoster": (6, 20),
    "TownNightDataCityPoster": (23, 11),
    "TownNightPillar": (24, 48),
    "TownNightClothingSign": (37, 21),
    "TownNightStoreSign": (45, 21),
    "TownNightGrave": (13, 40),
    "TownNightNPCSleep": (17, 37),
    "TownNightNPCParty": (18, 36),
    "TownNightTABLON": (18, 34),
    "TownNightNPCLoveIt": (17, 36),
    "TownNightNPCWhatALovelyNight": (15, 8),
    "TownNightSorryWeAreClosing": (36, 21),
    "TownNightEhhhYouuuuuuuuu": (41, 37),
    "InnNightToInnRoomsNight": (1, 0),
    "InnNightToTownNight": (8, 12),
    "InnNightpapelesposada": (14, 11),
    "InnNightpan": (12, 6),
    "InnRoomsNightToInnNight": (6, 18),
    "InnRoomsNightSleep": (12, 9),
    "InnRoomsNightIchaIchaParadiseAuthorJiraiya": (18, 15),
    "Town2BoarInn": (29, 21),
    "Town2ToInn": (28, 20),
    "Town2ToRiver": (49, 23),
    "Town2CorruptionCounter": (20, 27),
    "Town2ToBar2": (25, 45),
    "Town2ToFoodStore": (43, 20),
    "Town2ToClothingStore": (36, 20),
    "Town2ToHouseInterior": (6, 27),
    "Town2SeemsItsClosed": (13, 32),
    "Town2NPCWorkersSon": (45, 43),
    "Town2CastlePoster": (10, 6),
    "Town2MeetPhotographer": (18, 10),
    "Town2ToRiverEvent": (48, 24),
    "Town2NPCCop": (17, 45),
    "Town2NPCtourist1": (16, 36),
    "Town2borrachoinconsciente": (41, 45),
    "Town2Stall": (13, 20),
    "Town2Merchant": (9, 20),
    "Town2FleaMarket": (17, 20),
    "Town2NPCWomanAdvice": (7, 36),
    "Town2LeynaJohanSex": (21, 14),
    "Town2TABLON": (18, 34),
    "Town2IHaveToFindThatGuy": (28, 21),
    "Town2chicoencontrado": (43, 34),
    "Town2NPCCantWait": (9, 27),
    "Town2mafioso": (50, 33),
    "Town2borracho": (45, 40),
    "Town2NPCVillager": (4, 45),
    "Town2ToPoliceStation": (3, 20),
    "Town2PolicePoster": (6, 20),
    "Town2DataCityPoster": (23, 11),
    "Town2Pillar": (24, 48),
    "Town2chicofestival": (46, 31),
    "Town2NPCAnotherFestivalBoy": (1, 38),
    "Town2NPCFountainGuy": (22, 8),
    "Town2hombrepaseando3": (24, 21),
    "Town2ClothingSign": (37, 21),
    "Town2StoreSign": (45, 21),
    "Town2ToPath": (0, 21),
    "Town2fotografo": (18, 5),
    "Town2ToGlade": (49, 42),
    "Town2Grave": (13, 40),
    "Town2CorruptionFairy": (21, 27),
    "Town2NPCPissedUp": (38, 28),
    "Town2Ah": (40, 28),
    "Town2HeySweetieDoYouWantToHaveAGoodTime": (29, 29),
    "Town2ToTownEntrance": (20, 49),
    "Bar2ToTown2": (8, 12),
    "Bar2barman": (6, 4),
    "Bar2NPCMachine": (12, 3),
    "Bar2NPCBuyDrink": (8, 3),
    "Bar2NPCOldDrunk": (15, 4),
    "Bar2NPCDadComplains": (1, 7),
    "Bar2NPCBadFood": (1, 9),
    "MountainsYouWonANewObject": (7, 5),
    "MountainsYouWonANewObject_v2": (6, 7),
    "MountainsYouWonANewObject_v3": (7, 8),
    "MountainsYouWonANewObject_v4": (9, 8),
    "MassageParlorToFestival": (7, 12),
    "TownFestivalNightBoarInn": (29, 21),
    "TownFestivalNightToInnNight": (28, 20),
    "TownFestivalNightStoreClosed": (44, 20),
    "TownFestivalNightimpedimento": (28, 21),
    "TownFestivalNightSeemsItsClosed": (13, 32),
    "TownFestivalNightCastlePoster": (10, 6),
    "TownFestivalNightPoliceAsleep": (3, 20),
    "TownFestivalNightPolicePoster": (6, 20),
    "TownFestivalNightDataCityPoster": (23, 11),
    "TownFestivalNightPillar": (24, 48),
    "TownFestivalNightClothingSign": (37, 21),
    "TownFestivalNightStoreSign": (45, 21),
    "TownFestivalNightCorruptionCounter": (20, 27),
    "TownFestivalNightGrave": (13, 40),
    "TownFestivalNightNPCWhatALovelyNight": (15, 8),
    "TownFestivalNightOooohThisBeerIsGreatHehehehe": (19, 9),
    "TownFestivalNightGoodNightCouple": (26, 28),
    "TownFestivalNightTheFoodIsGoodButTheWineCouldBeBetter": (23, 32),
    "TownFestivalNightThisFoodIsAmazingYouHaveToTryThis": (18, 32),
    "TownFestivalNightGodBlessThisFestivitieHehehe": (19, 33),
    "TownFestivalNightHeyLeaveMeAlonePlease": (6, 45),
    "TownFestivalNightIOverdidItWithTheLiquorMyWifeIsGoingToKillMe": (38, 45),
    "TownFestivalNightWhereTheHellHaveMyFriendsGone": (23, 38),
    "TownFestivalNightShhhhImMeetingAVeryCuteTourist": (32, 32),
    "TownFestivalNightUgghghhh": (27, 38),
    "TownFestivalNightPartyyyy": (38, 37),
    "TownFestivalNightMinesBigger": (13, 25),
    "TownFestivalNightNoMinesWaaaayBiggerPal": (10, 26),
    "TownFestivalNighteventoblackmail": (40, 37),
    "TownFestivalNighteventoescondite": (19, 29),
    "TownFestivalNightHesDrunkAgainMyHusbandCantHoldHisLiquor": (19, 7),
    "TownFestivalNightIShouldLookForJohanThisGameHasGoneLongerThanIdLike": (47, 30),
    "FestivalNightnosalida": (12, 0),
    "FestivalNightasd": (6, 9),
    "FestivalNightFoodStand": (19, 12),
    "FestivalNightWheresMyFriendGoneAFewMinutesAgoHeWasHereEatingAHotDog": (19, 4),
    "FestivalNightNPCVomit": (3, 7),
    "FestivalNightThosePillsTheyGaveMeToHellWithThem": (25, 8),
    "FestivalNightOhHeHelloHideTheErectionIHopeSheWillNotNotice": (13, 9),
    "FestivalNightGoodNightLeynayouAreAsSexyAsEver": (12, 9),
    "FestivalNightICantGoDressedLikeThisWhatWouldJohanThink": (5, 9),
    "FestivalNightLeynaropa": (12, 1),
    "FestivalNightMassageParlor": (5, 15),
    "FestivalFinaleYoSlap": (10, 15),
    "FestivalFinaleHeyLeynaGoodToSeeYouHere": (3, 12),
    "FestivalFinaleDoYouWantSomeMasksForTheFinalEvent": (7, 6),
    "FestivalFinaleHeyGoodToSeeYouLeynaEspeciallyInThisSituationHehehehehe": (23, 3),
    "FestivalFinaleOhLeynaIWasHopingToMeetYouIHaveSomethingToGiveYou": (6, 4),
    "FestivalFinaleHeyWhatsGoingOnHere": (22, 19),
    "FestivalFinaleevent_15": (10, 20),
    "FestivalFinaleToCasinoFinale": (3, 21),
    "FestivalFinaleAMassageWait": (5, 15),
    "ApartmentEndingORDENADOR": (6, 3),
    "ApartmentEndingtelevision": (5, 8),
    "ApartmentEndingarmario": (3, 7),
    "ApartmentEndinglavabo": (14, 8),
    "ApartmentEndingpuerta": (1, 12),
    "ApartmentGroundFloortelevision": (5, 8),
    "ApartmentGroundFloorarmario": (3, 7),
    "ApartmentGroundFloorlavabo": (14, 8),
}
