define Leyna = Character("Leyna", color="#fa7a4b")
define Johan = Character("Johan", color="#65cc41")
define Prisoner = Character("Prisoner", color="#65cc41")
define Alexa = Character("Alexa", color="#ffffa3")
define Innkeeper = Character("Innkeeper", color="#bbbbbb")
define Grandson = Character("Grandson", color="#bbbbbb")
define Thug = Character("Thug", color="#bbbbbb")
define Kid = Character("Kid", color="#bbbbbb")
define Husband = Character("Husband", color="#bbbbbb")
define Wife = Character("Wife", color="#bbbbbb")
define OldMan = Character("Old man", color="#bbbbbb")
define DrunkOldMan = Character("Drunk old man", color="#bbbbbb")
define OldVillager = Character("Old villager", color="#bbbbbb")
define NakedVillager = Character("Naked villager", color="#bbbbbb")
define YoungVillager = Character("Young villager", color="#bbbbbb")
define YoungVillager2 = Character("Young villager 2", color="#bbbbbb")
define YoungVillager3 = Character("Young villager 3", color="#bbbbbb")
define Villager = Character("Villager", color="#bbbbbb")
define Villager1 = Character("Villager 1", color="#bbbbbb")
define Villager2 = Character("Villager 2", color="#bbbbbb")
define Villager3 = Character("Villager 3", color="#bbbbbb")
define MaleVoice = Character("Male voice", color="#bbbbbb")
define FemaleVoice = Character("Female voice", color="#bbbbbb")
define Unknown = Character("???", color="#bbbbbb")
define VillagerWoman = Character("Villager woman", color="#bbbbbb")
define VillagerMan = Character("Villager man", color="#bbbbbb")
define DrunkVillager = Character("Drunk villager", color="#bbbbbb")
define DrunkVillager2 = Character("Drunk villager 2", color="#bbbbbb")
define VillagerGirl = Character("Villager girl", color="#bbbbbb")
define Barman = Character("Barman", color="#bbbbbb")
define Receptionist = Character("Receptionist", color="#bbbbbb")
define DrunkTourist = Character("Drunk tourist", color="#bbbbbb")
define OldWoman = Character("Old woman", color="#bbbbbb")
define Tourist = Character("Tourist", color="#bbbbbb")
define Policeman = Character("Policeman", color="#bbbbbb")
define John = Character("John", color="#bbbbbb")
define Boy = Character("Boy", color="#bbbbbb")
define Officer = Character("Officer", color="#bbbbbb")
define PoliceCaptain = Character("Police captain", color="#bbbbbb")
define WomansVoice = Character("(Woman's voice)", color="#bbbbbb")
define Laura = Character("Laura", color="#bbbbbb")
define TV = Character("TV", color="#bbbbbb")
define Merchant = Character("Merchant", color="#bbbbbb")
define AlexasHusband = Character("Alexa's husband", color="#65cc41")
define WorkersSon = Character("Worker's son", color="#bbbbbb")
define Worker = Character("Worker", color="#bbbbbb")
define Villagers = Character("Villagers", color="#bbbbbb")
define Friend = Character("Friend", color="#bbbbbb")
define TouristWoman = Character("Tourist woman", color="#bbbbbb")
define Kevin = Character("Kevin", color="#bbbbbb")
define Daniela = Character("Daniela", color="#bbbbbb")
define CutMeOwnThroatDibbler = Character("Cut-Me-Own-Throat Dibbler", color="#bbbbbb")


