init python:

    def get_person_image(event, title):
        return None if event not in face_images else face_images[event]

    def is_person(event, title):
        return get_person_image(event, title) != None

    def is_event_image(event):
        return get_event_choice_image(event) != None

    def get_event_choice_image(event, priority = None, text = ""):
        # if event == "OShannonsEddie" and seen_today("OShannonsEddie"):
        #     return None
        # if event == "OShannonsAndy" and switch("jessie_oshannons"):
        #     return "oshannonsandyjessie_choice"
        if renpy.loadable("images/" + "choices/" + event.lower() + "_choice.webp"):
            return event.lower() + "_choice"
        elif priority != None and renpy.loadable("images/" + "choices/" + event.lower() + "_priority_choice.webp"):
            return event.lower() + "_priority_choice"
        return None if event not in event_images else event_images[event]

define event_images = {
}

define large_face_images = {
    "north": (64, 76),
    "northeast": (64, 64),
    "northwest": (64, 64),
    "south": (64, 76),
    "southeast": (64, 64),
    "southwest": (64, 64),
    "west": (76, 64),
    "east": (76, 64),
    "leyna108": (108, 360),
    "apartment_laptop": (166, 175),
    "apartment_tv": (171, 129),
    "apartment_drink": (58, 68),
    "glade_note": (46, 69),
    "innkeeper": (111, 270),
    "hot_springs_sign": (70,56),
    "inn_bread": (41,18),
    "inn_papers": (29,58),
    "inn_rooms_book": (82,28),
    "inn_rooms_door": (125,624),
    "inn_rooms_other": (21,247),
    "inn_room_door": (155,440),
    "inn_room_suitcase": (200,198),
    "inn_man1": (47,84),
    "inn_man2": (40,67),
    "inn_woman": (58,129),
    "inn_rooms_woman": (71,245),
    "photographer": (53,211),
    "tourist3": (67,227),
    "drunk": (111,330),
    "drunk_other": (90,307),
    "jack": (44,131),
    "alexa": (128,228),
    "kid": (123,249),
    "skirtlift": (249,424),
    "cop1": (98,290),
    "cop2": (204,400),
    "cop3": (180,417),
    "bag": (140,342),
    "dad": (155,338),
    "stall": (64,171),
    "flea": (32,143),
    "old_drunk": (110,269),
    "house_woman": (111,378),
    "house_man": (120,322),
    "merchant": (129,270),
    "officesuit": (163,598),
    "mafia": (40,169),
    "relax": (107,300),
    "fairy": (145,160),
    "pass_out": (102,41),
    "johan": (84,247),
    "path_sign": (92,70),
    "what_to_do": (185,180),
    "what_to_do_night": (185,180),
    "inn_sign": (49,59),
    "inn_sign_night": (49,59),
    "inn_door": (103,158),
    "inn_door_night": (103,158),
    "police_sign": (56,67),
    "police_sign_night": (50,64),
    "police_door": (67,178),
    "police_door_night": (67,178),
    "barn_door": (137,323),
    "barn_door_night": (137,323),
    "statue": (322,278),
    "statue_night": (322,278),
    "pillar": (70,61),
    "pillar_night": (70,61),
    "grave": (24,37),
    "grave_night": (24,37),
    "locked_door": (17,33),
    "locked_door_night": (17,33),
    "happy_pig": (67,75),
    "happy_pig_night": (67,75),
    "general_store": (43,80),
    "general_store_night": (43,80),
    "clothes_door": (69,297),
    "clothes_door_night": (69,297),
    "store_door": (45,131),
    "store_door_night": (45,131),
    "castle_sign": (68,44),
    "castle_sign_night": (68,44),
    "north_sign": (46,35),
    "north_sign_night": (46,35),
    "bar_door": (50,147),
    "bed": (271,127),
    "town_old_man": (87,202),
    "town_want_women": (62,184),
    "town_cheap": (89,330),
    "wild": (76,172),
    "town_old_woman": (61, 175),
    "town_villager": (59,132),
    "worker": (70,240),
    "town_guy": (116, 320),
    "bartender": (87, 193),
    "path_flower1": (130, 154),
    "path_flower2": (120, 126),
    "path_flower3": (126, 91),
    "path_flower4": (129, 78),
    "askance": (92, 114),
    "backwhit": (90, 305),
    "chillin": (112, 388),
    "barflies": (262, 289),
    "barflies2": (262, 289),
    "barflies3": (262, 289),
    "machine": (44, 108),
    "jacket": (122, 343),
    "abusive": (88, 250),
    "complain_dad": (119, 335),
    "complain_son": (84, 356),
    "clothes_merchant": (190, 473),
    "clothes": (114, 353),
    "store_merchant": (108,303),
    "store_drinks": (153, 131),
    "store_food": (216, 228),
    "tool_bag": (70, 64),
    "naked_river": (263, 550),
    "naked_river2": (112, 187),
    "naked_river3": (237, 280),
    "cat": (60, 86),
    "well": (66, 10),
    "festival_man": (80, 255),
    "festival_son": (56, 222),
    "festival_clothes": (235, 121),
    "bar_table": (584, 99),
    "receptionist": (115, 202),
    "cell": (234, 459),
    "prisoner": (88, 313),
    "festivaljohan": (63, 248),
    "festivaljohan2": (63, 248),
    "festivalalexa": (20, 64),
    "festival1": (130, 289),
    "festival2": (79, 233),
    "festival3": (76, 299),
    "festival4": (82, 300),
    "festival5": (114, 333),
    "festival6": (131, 288),
    "festival7": (97, 256),
    "festivalboy": (56, 240),
    "festivalhubby": (92, 313),
    "massagedoor": (37, 50),
    "ritualboy1": (32, 102),
    "foundboy": (14, 61),
    "festinight_oldman": (38, 103),
    "festinight_oldman2": (69, 219),
    "festinight_couple": (156, 300),
    "festinight_olddrunk": (49, 192),
    "festinight_back1": (80, 268),
    "festinight_drinker": (93, 253),
    "festinight_womantry": (90, 192),
    "night_black": (60, 137),
    "black_vee": (46, 144),
    "nopants": (59, 222),
    "armsup": (71, 232),
    "nightboys": (146, 300),
    "backtourist": (43,132),
    "festinight_thug": (47, 166),
    "festinight_wait": (96, 213),
    "festinight_wife": (61, 244),
    "nudenight1": (146, 244),
    "nudenight2": (198, 246),
    "alexahusbandnight": (112, 190),
    "festibar": (378, 186),
    "night_man": (61, 160),
    "chef": (73, 212),
    "ill": (62, 122),
    "naked1": (130, 242),
    "naked2": (164, 266),
    "naked3": (115, 259),
    "naked4": (157, 280),
    "naked_photographer": (101, 247),
    "group": (330, 265),
    "slap": (129, 290),
    "southy": (64, 76),
    "massage_night": (122, 83),
    "alexa_bar": (188, 336),
    "blond_night": (100, 290),
    "festinight_man": (120, 278),
    "festinight_back": (152, 320),
    "festinight_drunk": (109, 280),
    "festinight_pills": (131, 232),
    "drunk_two": (126, 233),
    "ah": (63, 211),
    "sup": (92, 250),
}

define face_image_hack_offsets = {
    "tourist3": (1, 1),
    "house_woman": (1, 1),
    "bartender": (1, 1),
    "backwhit": (1, 1),
    "barflies": (1, 1),
    "barflies2": (1, 1),
    "barflies3": (1, 1),
    "jacket": (1, 1),
    "complain_son": (1, 1),
    "johan": (1, 1),
    "festivalhubby": (1, 1),
    "festival7": (1, 1),
    "foundboy": (1, 1),
    "festinight_couple": (1, 1),
    "festinight_drinker": (1, 1),
    "festinight_womantry": (1, 1),
    "festinight_wife": (1, 1),
    "nudenight1": (1, 1),
    "nudenight2": (1, 1),
    "alexa_bar": (1, 1),
    "ill": (1, 1),
    "drunk_two": (1, 1),
    "sup": (1, 1),
}

define map_event_zorder = {
    "BarNPCthug1": 1000,
    "BarNPCthug2": 1001,
    "BarNPCthug5": 1002,
    "BarNPCMachine": 1,
    "Bar2NPCMachine": 1,
    "BarNPCOldDrunk": 999,
    "BarNPCAbusive": 3,
    "BarNPCBadFood": 2,
    "BarNPCDadComplains": 4,
    "RiverNPCEntranceMan": 1000,
    "PoliceStationPrisoner": 1,
    "PoliceStationBars": 2,
    "Townborrachoinconsciente": 1,
    "Town2borrachoinconsciente": 1,
    "FestivalButtPlugEvent": 1,
    "FestivalNightNPCVomit": 1,
}

define face_images = {
    "ApartmentORDENADOR": "apartment_laptop",
    "ApartmentEndingORDENADOR": "apartment_laptop",
    "ApartmentNPCMUJER": "leyna108",
    "Apartmentarmario": "southwest",
    "ApartmentEndingarmario": "southwest",
    "ApartmentGroundFloorarmario": "southwest",
    "Apartmenttelevision": "apartment_tv",
    "ApartmentEndingtelevision": "apartment_tv",
    "ApartmentGroundFloortelevision": "apartment_tv",
    "Apartmentlavabo": "apartment_drink",
    "ApartmentEndinglavabo": "apartment_drink",
    "ApartmentGroundFloorlavabo": "apartment_drink",
    "Apartmentpuerta": "west",
    "ApartmentEndingpuerta": "west",
    "ApartmentGroundFloorpuerta": "west",

    "GladeWelcomeToTheCumZone": "glade_note",
    "GladeToTown": "south",

    "Innposadero": "innkeeper",
    "InnNightpapelesposada": "inn_papers",
    "Innpan": "inn_bread",
    "InnNightpan": "inn_bread",
    "InnToInnRooms": "northeast",
    "InnNightToInnRoomsNight": "northeast",
    "InnToTown": "south",
    "InnNightToTownNight": "south",
    "InnCantLeave": "south",
    "InnNPCDrinker": "inn_man1",
    "InnNPCDiner": "inn_man2",
    "InnNPCEater": "inn_woman",
    "Innpapelesposada": "inn_papers",

    "InnRoomsIchaIchaParadiseAuthorJiraiya": "inn_rooms_book",
    "InnRoomsNightIchaIchaParadiseAuthorJiraiya": "inn_rooms_book",
    "InnRoomsDEJANDOlasmaletas": "inn_rooms_door",
    "InnRoomsToInnRoom": "inn_rooms_door",
    "InnRoomsnio": "inn_rooms_other",
    "InnRoomsRoomToHallway": "inn_room_door",
    "InnRoomsToInn": "south",
    "InnRoomsNightToInnNight": "south",
    "InnRoomspersonabao": "inn_rooms_woman",
    "InnRoomsSleep": "bed",
    "InnRoomsNightSleep": "bed",

    "TownCenterToNorth": "north",
    "TownIShouldGoToTheInnJohannIsWaitingForMe_v10": "north",
    "TownCenterToEast": "east",
    "TownCenterToSouth": "south",
    "TownIShouldGoToTheInnJohannIsWaitingForMe_v12": "south",
    "TownCenterToCenterWest": "west",
    "TownIShouldGoToTheInnJohannIsWaitingForMe_v11": "west",
    "Town2CenterToNorth": "north",
    "Town2CenterToEast": "east",
    "Town2CenterToSouth": "south",
    "Town2CenterToCenterWest": "west",
    "TownNightCenterToNorth": "north",
    "TownNightCenterToEast": "east",
    "TownNightCenterToSouth": "south",
    "TownNightCenterToCenterWest": "west",
    "TownFestivalNightCenterToNorth": "north",
    "TownFestivalNightCenterToEast": "east",
    "TownFestivalNightCenterToSouth": "south",
    "TownFestivalNightCenterToCenterWest": "west",
    "TownSouthToCenter": "north",
    "Town2SouthToCenter": "north",
    "TownNightSouthToCenter": "north",
    "TownFestivalNightSouthToCenter": "north",
    "TownSouthToSouthEast": "southeast",
    "Town2SouthToSouthEast": "southeast",
    "TownNightSouthToSouthEast": "southeast",
    "TownFestivalNightSouthToSouthEast": "southeast",
    "TownSouthEastToSouth": "west",
    "Town2SouthEastToSouth": "west",
    "TownNightSouthEastToSouth": "west",
    "TownFestivalNightSouthEastToSouth": "west",
    "TownEastToSouthEast": "southeast",
    "TownIShouldGoToTheInnJohannIsWaitingForMe": "southeast",
    "Town2EastToSouthEast": "southeast",
    "TownNightEastToSouthEast": "southeast",
    "TownFestivalNightEastToSouthEast": "southeast",
    "TownSouthEastToEast": "northwest",
    "Town2SouthEastToEast": "northwest",
    "TownNightSouthEastToEast": "northwest",
    "TownFestivalNightSouthEastToEast": "northwest",
    "TownCenterWestToCenter": "east",
    "TownCenterWestToWest": "northwest",
    "Town2CenterWestToCenter": "east",
    "Town2CenterWestToWest": "northwest",
    "TownNightCenterWestToCenter": "east",
    "TownNightCenterWestToWest": "northwest",
    "TownFestivalNightCenterWestToCenter": "east",
    "TownFestivalNightCenterWestToWest": "northwest",
    "TownWestToCenter": "south",
    "Town2WestToCenter": "south",
    "TownNightWestToCenter": "south",
    "TownFestivalNightWestToCenter": "south",
    "TownEastToCenter": "south",
    "Town2EastToCenter": "south",
    "TownNightEastToCenter": "south",
    "TownFestivalNightEastToCenter": "south",
    "TownFestivalNightIShouldLookForJohanThisGameHasGoneLongerThanIdLike": "south",
    "TownToGlade": "north",
    "Town2ToGlade": "north",
    "TownNightToGlade": "north",
    "TownFestivalNightToGlade": "north",
    "TownToRiverEvent": "north",
    "Town2ToRiverEvent": "north",
    "TownToRiver": "north",
    "Town2ToRiver": "north",
    "TownNorthToCenter": "south",
    "Town2NorthToCenter": "south",
    "TownFestivalNightNorthToCenter": "south",
    "TownNightNorthToCenter": "south",
    "TownToPath": "northwest",
    "Town2ToPath": "northwest",
    "Townespacioentradafestival": "northwest",
    "HouseInteriorToTown": "south",
    "BarToTown": "south",
    "Bar2ToTown": "south",
    "Bar2ToTown2": "south",

    "Townfinaldelprimerdia": "johan",
    "InnJohanEndOfDay2": "johan",

    "TownCorruptionFairy": "fairy",
    "Town2CorruptionFairy": "fairy",
    "Towneventofotografiaintro": "photographer",
    "Townfotografo": "photographer",
    "Town2fotografo": "photographer",
    "Town2MeetPhotographer": "photographer",
    "TownNPCwoman": "alexa",
    "TownMeetAlexa": "alexa",
    "TownNPCkid": "kid",
    "TownNPCPADRE": "dad",
    "TownMerchant": "merchant",
    "Town2Merchant": "merchant",
    "TownNPCCantWait": "officesuit",
    "Town2NPCCantWait": "officesuit",
    "TownNPCmafioso": "mafia",
    "Town2mafioso": "mafia",
    "Town2NPCFountainGuy": "relax",
    "TownNPCRelax": "relax",

    "HotSpringsExteriorHotSpings": "hot_springs_sign",
    "HotSpringsExteriorToReception": "northwest",
    "HotSpringsExteriorToPath": "southwest",

    "PoliceStationToTown": "south",
    "ClothingStoreToTown": "south",
    "FoodStoreToTown": "south",

    "TownTABLON": "what_to_do",
    "Town2TABLON": "what_to_do",
    "TownNightTABLON": "what_to_do_night",
    "TownFestivalNightTABLON": "what_to_do_night",
    "TownClothingSign": "happy_pig",
    "Town2ClothingSign": "happy_pig",
    "TownNightClothingSign": "happy_pig_night",
    "TownFestivalNightClothingSign": "happy_pig_night",
    "TownStoreSign": "general_store",
    "Town2StoreSign": "general_store",
    "TownNightStoreSign": "general_store_night",
    "TownFestivalNightStoreSign": "general_store_night",
    "TownPolicePoster": "police_sign",
    "Town2PolicePoster": "police_sign",
    "TownNightPolicePoster": "police_sign_night",
    "TownFestivalNightPolicePoster": "police_sign_night",
    "TownToPoliceStation": "police_door",
    "Town2ToPoliceStation": "police_door",
    "TownNightPoliceAsleep": "police_door_night",
    "TownFestivalNightPoliceAsleep": "police_door_night",
    "TownToHouseInterior": "barn_door",
    "Town2ToHouseInterior": "barn_door",
    "TownNightToHouseInterior": "barn_door_night",
    "TownFestivalNightToHouseInterior": "barn_door_night",
    "TownBoarInn": "inn_sign",
    "Town2BoarInn": "inn_sign",
    "TownNightBoarInn": "inn_sign_night",
    "TownFestivalNightBoarInn": "inn_sign_night",
    "TownPillar": "pillar",
    "Town2Pillar": "pillar",
    "TownNightPillar": "pillar_night",
    "TownFestivalNightPillar": "pillar_night",
    "TownToInn": "inn_door",
    "Town2ToInn": "inn_door",
    "Town2IHaveToFindThatGuy": "inn_door",
    "TownNightToInnNight": "inn_door_night",
    "TownFestivalNightimpedimento": "inn_door_night",
    "TownFestivalNightToInnNight": "inn_door_night",
    "TownCorruptionCounter": "statue",
    "Town2CorruptionCounter": "statue",
    "TownNightCorruptionCounter": "statue_night",
    "TownFestivalNightCorruptionCounter": "statue_night",
    "TownGrave": "grave",
    "Town2Grave": "grave",
    "TownNightGrave": "grave_night",
    "TownFestivalNightGrave": "grave_night",
    "TownSeemsItsClosed": "locked_door",
    "Town2SeemsItsClosed": "locked_door",
    "TownNightSeemsItsClosed": "locked_door_night",
    "TownFestivalNightSeemsItsClosed": "locked_door_night",
    "TownToClothingStore": "clothes_door",
    "Town2ToClothingStore": "clothes_door",
    "TownNightSorryWeAreClosing": "clothes_door_night",
    "TownFestivalNightSorryWeAreClosing": "clothes_door_night",
    "TownToFoodStore": "store_door",
    "Town2ToFoodStore": "store_door",
    "TownNightStoreClosed": "store_door_night",
    "TownFestivalNightStoreClosed": "store_door_night",
    "TownCastlePoster": "castle_sign",
    "Town2CastlePoster": "castle_sign",
    "TownNightCastlePoster": "castle_sign_night",
    "TownFestivalNightCastlePoster": "castle_sign_night",
    "TownDataCityPoster": "north_sign",
    "Town2DataCityPoster": "north_sign",
    "TownNightDataCityPoster": "north_sign_night",
    "TownFestivalNightDataCityPoster": "north_sign_night",
    "TownToBar": "bar_door",
    "Town2ToBar2": "bar_door",
    "TownNPCOldMan": "town_old_man",
    "Townturista1": "town_want_women",
    "Town2NPCtourist1": "town_want_women",
    "Townturista1_v2": "town_cheap",
    "TownNPCVillageWoman": "wild",
    "Town2NPCWomanAdvice": "wild",
    "TownNPCVillager": "town_villager",
    "Town2NPCVillager": "town_villager",
    "TownStall": "stall",
    "Town2Stall": "stall",
    "TownFleaMarket": "flea",
    "Town2FleaMarket": "flea",
    "TownSkirtLift": "skirtlift",
    "TownNPCCop": "cop1",
    "Town2NPCCop": "cop1",
    "TownNPCBrowser": "bag",
    "Townborrachoinconsciente": "pass_out",
    "Town2borrachoinconsciente": "pass_out",
    "TownNPCtourist3": "tourist3",
    "TownNPCDrunkEvent2": "drunk_other",
    "Townhombrepaseando3": "jack",
    "Town2hombrepaseando3": "jack",
    "Townborracho": "old_drunk",
    "Town2borracho": "old_drunk",
    "Towneventolemetenmanobarrio": "drunk",
    "TownNPCDrunkEvent1": "drunk",
    "TownNPCEntryFestival": "worker",
    "TownNPCtourist2": "town_guy",

    "PoliceStationSorryYouCantBeHerePleaseGoToTheHall": "cop2",
    "PoliceStationNPCCaptain": "cop3",
    "HouseInteriormujercasa1": "house_woman",
    "HouseInteriorpersonacasa1": "house_man",

    "MountainsYouWonANewObject": "path_flower1",
    "MountainsYouWonANewObject_v2": "path_flower2",
    "MountainsYouWonANewObject_v3": "path_flower3",
    "MountainsYouWonANewObject_v4": "path_flower4",

    "BarBJGame": "bar_table",
    "Barbarman": "bartender",
    "Bar2barman": "bartender",
    "BarNPCBuyDrink": "askance",
    "Bar2NPCBuyDrink": "askance",
    "BarNPCthug3": "backwhit",
    "BarNPCthug4": "chillin",
    "BarNPCthug1": "barflies",
    "BarNPCthug2": "barflies2",
    "BarNPCthug5": "barflies3",
    "BarNPCMachine": "machine",
    "Bar2NPCMachine": "machine",
    "BarNPCOldDrunk": "jacket",
    "Bar2NPCOldDrunk": "jacket",
    "BarNPCAbusive": "abusive",
    "BarNPCBadFood": "complain_dad",
    "Bar2NPCBadFood": "complain_dad",
    "BarNPCDadComplains": "complain_son",
    "Bar2NPCDadComplains": "complain_son",
    "ClothingStoreHeyThere": "clothes_merchant",
    "FoodStoreMerchant": "store_merchant",
    "ClothingStoreIShouldComeBackLaterToTryTheFestivalClothes": "festival_clothes",
    "FoodStoreTheyHaveSoftDrinksOfAllFlavors": "store_drinks",
    "FoodStoreMmmSpicyNoodles": "store_food",
    "FoodStoreYouWonANewObject": "tool_bag",
    "FoodStoreToolbag": "tool_bag",
    "RiverNPCEntranceMan": "naked_river",
    "RiverNPCEventMan": "naked_river2",
    "RiverNPCRiverBucket": "naked_river3",
    "Riverimpedimentoparasalirrio": "south",

    "PathHotSpringsTown": "path_sign",
    "PathToHotSpringsExterior": "east",
    "PathWowItLooksLikeTheHotspringsHaveReopened": "east",
    "PathLeynaWorkTrigger": "east",
    "PathToTown": "south",
    "PathMeow": "cat",
    "Pathespacioentradafestival": "north",
    "PathNPCFloat": "well",
    "PathNPCFestivalWorker": "festival_man",
    "PathNPCFestivalWorker2": "festival_man",
    "Festivalworkerdentrofestival": "festival_man",
    "Town2NPCWorkersSon": "festival_son",
        # ("PathNPCWow","NPCWow"),
    "Receptionrecepcion": "receptionist",
    "ReceptionToHotSpringsExterior": "southeast",
    "FestivalToPath": "west",
    "FestivalNightnosalida": "west",
    "FestivalNightLeynaropa": "west",
    "PoliceStationeventocomisaria": "cell",
    "PoliceStationPrisoner": "prisoner",
    "PoliceStationBars": "cell",

    "FestivalNorthToSouth": "east",
    "FestivalSouthToNorth": "west",
    "FestivalNightNorthToSouth": "east",
    "FestivalNightICantGoDressedLikeThisWhatWouldJohanThink": "east",
    "FestivalNightSouthToNorth": "west",
    "FestivalFinaleNorthToSouth": "east",
    "FestivalFinaleSouthToNorth": "west",

    "FestivalPhotoSession": "festivaljohan",
    "FestivalFoodStand": "festivaljohan2",
    "FestivalSpyOnAlexa": "festivalalexa",
    "FestivalNPCNiceTits": "festival1",
    "FestivalNPCShrooms": "festival2",
    "FestivalNPCSkint": "festival3",
    "FestivalNPCCompliment": "festival4",
    "FestivalNPCHeyCutie": "festival5",
    "FestivalNPCTourist": "festivalhubby",
    "FestivalNPCFruit": "festival6",
    "FestivalNPCLetch": "festival7",
    "FestivalFestivalWorkerSon": "festivalboy",
    "FestivalMassageParlor": "massagedoor",
    "FestivalFinaleAMassageWait": "massagedoor",
    "Town2chicofestival": "festivalboy",
    "Town2NPCAnotherFestivalBoy": "ritualboy1",
    "Town2chicoencontrado": "foundboy",
    "TownFestivalNightGoodNightCouple": "festinight_oldman",
    "TownFestivalNightUgghghhh": "festinight_oldman2",
    "TownNightNPCWhatALovelyNight": "festinight_couple",
    "TownFestivalNightNPCWhatALovelyNight": "festinight_couple",
    "TownFestivalNightIOverdidItWithTheLiquorMyWifeIsGoingToKillMe": "festinight_olddrunk",
    "TownFestivalNightTheFoodIsGoodButTheWineCouldBeBetter": "festinight_back1",
    "TownFestivalNightOooohThisBeerIsGreatHehehehe": "festinight_drinker",
    "TownFestivalNightThisFoodIsAmazingYouHaveToTryThis": "festinight_womantry",
    "TownNightNPCSleep": "night_black",
    "TownNightNPCLoveIt": "black_vee",
    "TownFestivalNightGodBlessThisFestivitieHehehe": "nopants",
    "TownFestivalNightPartyyyy": "armsup",
    "TownFestivalNighteventoblackmail": "nightboys",
    "TownFestivalNightWhereTheHellHaveMyFriendsGone": "backtourist",
    "TownFestivalNightHeyLeaveMeAlonePlease": "festinight_thug",
    "TownFestivalNightShhhhImMeetingAVeryCuteTourist": "festinight_wait",
    "TownFestivalNightHesDrunkAgainMyHusbandCantHoldHisLiquor": "festinight_wife",
    "TownFestivalNightMinesBigger": "nudenight1",
    "TownFestivalNightNoMinesWaaaayBiggerPal": "nudenight2",
    "TownFestivalNighteventoescondite": "alexahusbandnight",
    "FestivalButtPlugEvent": "festibar",
    "TownNightEhhhYouuuuuuuuu": "nightboys",
    "TownNightBottleBoys": "nightboys",
    "TownNightNPCParty": "night_man",
    "FestivalNightFoodStand": "chef",
    "FestivalNightNPCVomit": "ill",
    "FestivalFinaleToCasinoFinale": "east",
    "FestivalFinaleChef": "chef",
    "FestivalFinaleHeyLeynaGoodToSeeYouHere": "naked1",
    "FestivalFinaleHeyGoodToSeeYouLeynaEspeciallyInThisSituationHehehehehe": "naked2",
    "FestivalFinaleOhLeynaIWasHopingToMeetYouIHaveSomethingToGiveYou": "naked3",
    "FestivalFinaleDoYouWantSomeMasksForTheFinalEvent": "naked4",
    "FestivalFinaleevent_15": "naked_photographer",
    "FestivalFinaleHeyWhatsGoingOnHere": "group",
    "FestivalFinaleHeyWhatsGoingOnHereDone": "group",
    "FestivalFinaleYoSlap": "slap",
    "Town2ToTownEntrance": "southy",
    "FestivalNightMassageParlor": "massage_night",
    "BarAlexa": "alexa_bar",
    "FestivalNightOhHeHelloHideTheErectionIHopeSheWillNotNotice": "blond_night",
    "FestivalNightWheresMyFriendGoneAFewMinutesAgoHeWasHereEatingAHotDog": "festinight_man",
    "FestivalNightasd": "festinight_back",
    "FestivalNightGoodNightLeynayouAreAsSexyAsEver": "festinight_drunk",
    "FestivalNightThosePillsTheyGaveMeToHellWithThem": "festinight_pills",
    "Town2HeySweetieDoYouWantToHaveAGoodTime": "drunk_two",
    "Town2Ah":"ah",
    "Town2NPCPissedUp": "sup",
}
